platform :ios, '8.0'
use_frameworks!

target "ToggleExample" do
  pod "AFNetworking", "~> 2.0"
  pod "Underscore.m"
  pod "ToggleHQ", :git => "https://github.com/togglehq/togglehq-ios-cocoapod.git", :branch => "feature/rename_groups_to_categories"
end
