target 'ToggleHQ_Example' do
  use_frameworks!

  pod 'ToggleHQ', :path => '../'
  # pod 'ToggleHQ', :path => '~/sites/upwork/togglehq-ios'
  # pod 'ToggleHQ', :git => 'https://github.com/togglehq/togglehq-ios.git'
end
